baseURL = 'https://riverportfolio.netlify.app'
languageCode = 'en-us'
title = 'River Romney'
theme = 'yassi'

[menu]
  [[menu.main]]
    name = "Home"
    pageRef = "/"
    weight = 10

  [[menu.main]]
    name = "Work"
    pageRef = "/projects"
    weight = 20

  [[menu.main]]
    name = "Writing"
    pageRef = "/posts"
    weight = 30

  [[menu.main]]
    name = "About"
    pageRef = "/about"
    weight = 40
    
[params]
# Homepage defaults 
showFeaturedProjects = false 
showBlogPosts = false

# Pages & Projects Meta defaults by section
showDatesProjects = false
showReadingTimeProjects = false
showCategoriesProjects = false
showTagsProjects = false
showSummaryProjects = false
showHeroImageProjects = false

showDatesPosts = true
showReadingTimePosts = true
showCategoriesPosts = true
showTagsPosts = true
showSummaryPosts = false
showHeroImagePosts = false

# Optional global fallbacks (used for other sections)
showDates = true
showReadingTime = true
showCategories = true
showTags = true
showSummary = false
showHeroImage = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

